version: '2'
services: 
  web: &web
    build: .
    env_file: .env
    depends_on:
      - "redis"
    ports:
      - "3000:3000"
  redis:
    image: redis:alpine
    ports:
      - "6379"
  mock-web:
    <<: *web
    volumes: 
      - ./mocks:/usr/mocks
  mock: 
    build: .
    env_file: .env
    depends_on:
      - "mock-web"
    volumes: 
      - ./mocks:/usr/mocks
