service: &default
  build: .
  env_file: .env
  links:
    - "redis"
  ports:
    - "3000"
redis:
  image: redis:3.2
  ports:
    - "6379"
web:
  build: .
  command: 'bash -c ''npm run'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
